// Full List (Hash) of Moonstone Supported Icons
//

export default {
	plus              : 0x0002B,  // plus
	minus             : 0x0002D,  // hyphen
	arrowhookleft     : 0x021A9,  // LeftArrowHook
	arrowhookright    : 0x021AA,  // RightArrowHook
	ellipsis          : 0x022EF,  // ellipsis
	check             : 0x02713,  // checkmark
	circle            : 0x0EFFDB, // record
	stop              : 0x0EFFDC, // stop
	play              : 0x0EFFDD, // play
	pause             : 0x0EFFDE, // pause
	forward           : 0x0EFFDF, // forward
	backward          : 0x0EFFE0, // rewind
	skipforward       : 0x0EFFE1, // skip_forward
	skipbackward      : 0x0EFFE2, // skip_backwards
	pauseforward      : 0x0EFFE3, // indicator_forward
	pausebackward     : 0x0EFFE4, // indicator_backward
	pausejumpforward  : 0x0EFFE5, // indicator_skip_forward
	pausejumpbackward : 0x0EFFE6, // indicator_skip_backward
	jumpforward       : 0x0EFFE7, // indicator_end
	jumpbackward      : 0x0EFFE8, // indicator_begin
	denselist         : 0x0EFFE9, // list_big
	bulletlist        : 0x0EFFEA, // list_bullets
	list              : 0x0EFFEB, // list_simple
	drawer            : 0x0EFFEC, // list_actions
	arrowlargedown    : 0x0EFFED, // caret_down_large
	arrowlargeup      : 0x0EFFEE, // caret_up_large
	arrowlargeleft    : 0x0EFFEF, // caret_left_large
	arrowlargeright   : 0x0EFFF0, // caret_right_large
	arrowsmallup      : 0x0EFFF1, // caret_up_small
	arrowsmalldown    : 0x0EFFF2, // caret_down_small
	arrowsmallleft    : 0x0EFFF3, // caret_left_small
	arrowsmallright   : 0x0EFFF4, // caret_right_small
	closex            : 0x0EFFF5, // close_x
	search            : 0x0EFFF6, // magnify
	rollforward       : 0x0EFFF7, // redo
	rollbackward      : 0x0EFFF8, // undo
	exitfullscreen    : 0x0EFFF9, // minimize
	fullscreen        : 0x0EFFFA, // maximize
	arrowshrinkleft   : 0x0EFFFB, // shrink_panel_left
	arrowshrinkright  : 0x0EFFFC, // shrink_panel_right
	arrowextend       : 0x0F0021, // arrow_left
	arrowshrink       : 0x0F0022, // arrow_right
	flag              : 0x0F0023, // flag
	funnel            : 0x0F0024, // filter
	trash             : 0x0F0025, // trash
	star              : 0x0F0028, // star_full
	hollowstar        : 0x0F0029, // star_empty
	halfstar          : 0x0F002A, // star_half
	gear              : 0x0F002B, // gear
	plug              : 0x0F002C, // input
	lock              : 0x0F002D,  // lock
	forward15         : 0x0F0041,  // forward15
	back15            : 0x0F0042,  // back15
	continousplay     : 0x0F0043,  // continous_play
	playlist          : 0x0F0044,  // playlist
	resumeplay        : 0x0F0045,  // resume_play
	image             : 0x0F0046,  // image
	audio             : 0x0F0061,  // audio
	music             : 0x0F0062,  // music
	languages         : 0x0F0081,  // languages
	cc                : 0x0F0082,  // cc
	ccon              : 0x0F0083,  // cc_on
	ccoff             : 0x0F0084,  // cc_off
	sub               : 0x0F0085,  // sub
	recordings        : 0x0F00A1,  // recordings
	livezoom          : 0x0F00A2,  // live_zoom
	liveplayback      : 0x0F00A3,  // live_playback
	liveplaybackoff   : 0x0F00A4,  // live_playback_off
	repeat            : 0x0F00A5,  // repeat
	repeatoff         : 0x0F00A6,  // repeat_off
	series            : 0x0F00A7,  // series
	repeatdownload    : 0x0F00A8,  // repeat_download
	view360           : 0x0F00A9,  // view_360
	view360off        : 0x0F00AA,  // view_360_off
	info              : 0x0F00AB,  // info
	repeattrack       : 0x0F00B1,  // repeat_track
	bluetoothoff      : 0x0F00B4,  // bluetooth_off
	verticalellipsis  : 0x0F00B5,  // vertical_ellipsis
	arrowcurveright   : 0x0F00B6,  // arrow_curve_right
	picture           : 0x0F00BA,  // picture
	home              : 0x0F00BB,  // home
	warning           : 0x0F00BC,  // warning
	scroll            : 0x0F00BD,  // scroll
	densedrawer       : 0x0F00BE,  // dense_drawer
	starminus         : 0x0F00BF,  // star_minus
	liverecord        : 0x0F00C1,  // live_record
	liveplay          : 0x0F00C2,  // live_play
	contrast          : 0x0F00C3,  // contrast
	edit              : 0x0F00C4,  // edit
	trashlock         : 0x0F00C7,  // trash_lock
	arrowrightskip    : 0x0F00CA,  // arrow_right_skip
	volumecycle       : 0x0F00CB,  // volume_cycle
	movecursor        : 0x0F00CC,  // move_cursor
	refresh           : 0x0F00CE,  // refresh
	question          : 0x0F00CF,  // question_mark
	questionreversed  : 0x0F00D0,  // reversed_question_mark
	s                 : 0x0F00D1,  // letter S
	repeatone         : 0x0F00DF,  // repeat_one
	repeatall         : 0x0F00E0,  // repeat_all
	repeatnone        : 0x0F00E1,  // repeat_none
	speakers          : 0x0F00E5,  // speakers
	koreansubtitles   : 0x0F00E8,  // korean_subtitles
	chinesesubtitles  : 0x0F00E9,  // chinese_subtitles
	arrowleftprevious : 0x0F00EC,  // arrow_left_previous
	searchfilled      : 0x0F00EE,  // search_filled
	zoomin            : 0x0F00EF,  // zoom_in
	zoomout           : 0x0F00F0,  // zoom_out
	playlistadd       : 0x0F00F1,  // playlist_add
	files             : 0x0F00F2,  // files
	arrowupdown       : 0x0F00F4,  // arrow_updown
	brightness        : 0x0F00F9,  // brightness
	download          : 0x0F00FA,  // download
	playlistedit      : 0x0F00FD,  // playlist_edit
	font              : 0x0F00FE,  // font
	musicon           : 0x0F00FF,  // music_on
	musicoff          : 0x0F0100,  // music_off
	liverecordone     : 0x0F0101,  // live_record_one
	liveflagone       : 0x0F0102,  // live_flag_one
	shuffle           : 0x0F0103,  // shuffle
	sleep             : 0x0F0104,  // sleep
	notification      : 0x0F0105,  // notification.001
	notificationoff   : 0x0F0106,  // notification
	checkselection    : 0x0F0107   // notification.002
};
