ignore:
    - "packages/i18n/src/Loader.js"
    - "packages/i18n/src/packedbuffer.js"
    - "packages/i18n/src/zoneinfo.js"
    - "packages/i18n/Text"
    - "packages/webos/signLang"
    - "packages/webos/speech"
    - "packages/webos/keyboard"
    - "packages/webos/platform"
    - "packages/webos/pmloglib"
    - "packages/webos/deviceinfo"
    - "packages/webos/application"
    - "packages/webos/LS2Request"
    - "packages/ui/Scrollable"
    - "packages/ui/Scroller/UiScrollerBase.js"
    - "packages/ui/GridListImageItem"
    - "packages/ui/Touchable/Pinch.js"
    - "packages/ui/VirtualList/VirtualListBase.js"
    - "packages/ui/VirtualList/UiVirtualListBase.js"

