ignore:
    - "packages/i18n/Text"
    - "packages/webos/speech"
    - "packages/webos/keyboard"
    - "packages/webos/platform"
    - "packages/webos/pmloglib"
    - "packages/webos/deviceinfo"
    - "packages/webos/application"
    - "packages/webos/LS2Request"
    - "packages/ui/Scrollable"
    - "packages/ui/GridListImageItem"

