ignore:
    - "packages/i18n/Text"
    - "packages/webos/speech"
    - "packages/webos/keyboard"
    - "packages/webos/platform"
    - "packages/webos/pmloglib"
    - "packages/webos/deviceinfo"
    - "packages/webos/application"
