ignore:
    - "packages/i18n/src/Loader.js"
    - "packages/i18n/src/packedbuffer.js"
    - "packages/i18n/src/zoneinfo.js"
    - "packages/i18n/Text"
    - "packages/webos/speech"
    - "packages/webos/keyboard"
    - "packages/webos/lastInputType"
    - "packages/webos/platform"
    - "packages/webos/pmloglib"
    - "packages/webos/deviceinfo"
    - "packages/webos/application"
    - "packages/webos/LS2Request"
    - "packages/ui/Touchable/Pinch.js"
    - "packages/webos/signlang"

