import kind from '@enact/core/kind';
import BodyText from '@enact/moonstone/BodyText';
import Button from '@enact/moonstone/Button';
import Icon from '@enact/moonstone/Icon';
import React, {PropTypes} from 'react';
import {storiesOf, action} from '@kadira/storybook';
import {withKnobs, boolean} from '@kadira/storybook-addon-knobs';
import css from './About.less';

const Pointer = kind({
	name: 'Pointer',

	propTypes: {
		pointDirection: PropTypes.string.isRequired,
		length: PropTypes.number
	},

	computed: {
		direction: ({pointDirection, length = 200}) => {
			switch (pointDirection) {
				case 'topLeft':
					return {
						width: length.toString(),
						height: '20',
						cx: '10',
						cy: '10',
						x1: '10',
						y1: '10',
						x2: length.toString(),
						y2: '10'
					};
				case 'bottomLeft':
					return {
						width: '20',
						height: length.toString(),
						cx: '10',
						cy: (length - 10).toString(),
						x1: '10',
						y1: '10',
						x2: '10',
						y2: (length - 10).toString()
					};
				case 'topRight':
					return {
						width: '20',
						height: length.toString(),
						cx: '10',
						cy: '10',
						x1: '10',
						y1: '10',
						x2: '10',
						y2: length.toString()
					};
			}
		}
	},

	render: ({direction, style}) => (
		<svg width={direction.width} height={direction.height} style={style}>
			<circle cx={direction.cx} cy={direction.cy} r='5' />
			<line x1={direction.x1} y1={direction.y1} x2={direction.x2} y2={direction.y2} />
		</svg>
	)
});

storiesOf('About Sampler')
	.addDecorator(withKnobs)
	.addWithInfo(
		' ',
		'A Tour of Sampler',
		() => (
			<div>
				<BodyText
					centered={boolean('text centered', false)}
				>
					Welcome to the Enact sampler! Explore Enact components.
				</BodyText>
				<Button onClick={action('onClick')} selected={boolean('button selected', false)}>
					Click me
				</Button>
				<div className={css.hintDialog} style={{top: '50', right: '-20px'}}>
					<Pointer pointDirection='topRight' length={30} style={{top: '-20', right: '25'}} />
					<div className={css.text}>
						Click <b>?</b> to see the live source code for the sample.
					</div>
				</div>
				<div className={css.hintDialog} style={{position: 'relative'}}>
					<Pointer pointDirection='topLeft' length={50} />
					<div className={css.text}>
						Select any component from the <b>sidebar</b> to see how they work.
					</div>
				</div>
				<div className={css.hintDialog} style={{bottom: '150px'}}>
					<Pointer pointDirection='bottomLeft' style={{left: '25px'}} />
					<div className={css.text}>
						<b>Action Logger</b> : log events generated by components
						<b>
							<Icon small className={css.icon}>arrowsmallup</Icon>
							Click the button above.
						</b>
					</div>
				</div>
				<div className={css.hintDialog} style={{bottom: '90px', left: '150px'}}>
					<Pointer pointDirection='bottomLeft' length={140} style={{left: '25px'}} />
					<div className={css.text}>
						<b>Backgrounds</b> : change background for visual reference.
					</div>
				</div>
				<div className={css.hintDialog} style={{bottom: '30px', left: '250px'}}>
					<Pointer pointDirection='bottomLeft' length={83} style={{left: '25px'}} />
					<div className={css.text}>
						<b>Knobs</b> : adjust component properties.
					</div>
				</div>
			</div>
		)
	);
