import {forProp, handle, not, stop} from '@enact/core/handle';

import {hasPointerMoved} from '../src/pointer';
import Spotlight from '../src/spotlight';
import type {NavigableFilter} from '../types/ContainerConfig';
import type {SpotlightContainerConfig} from '../types/SpotlightContainerConfig';
import type {
	SpotlightContainerAttributes,
	SpotlightContainerProps
} from '../types/SpotlightContainerProps';

const isNewPointerPosition = (ev: Event | null) => {
	if (!ev) return false;

	const {clientX, clientY} = ev as MouseEvent;
	return hasPointerMoved(clientX, clientY);
};

class SpotlightContainer {
	// set up context and props so we can use handle binding
	context = {};
	props: SpotlightContainerProps = {};

	id: string | null;
	canPreserveId: boolean | undefined;
	preserveId: boolean;
	config: SpotlightContainerConfig['containerConfig'];
	filter: NavigableFilter | undefined;
	attr: SpotlightContainerAttributes;
	shouldPreventBlur: boolean;

	constructor ({containerConfig, navigableFilter, preserveId}: SpotlightContainerConfig = {}) {
		// spotlight id - set either via props or generated by Spotlight
		this.id = null;

		// Preserve the spotlight id across instances when it is set via props and preserveId is set
		this.canPreserveId = preserveId;
		this.preserveId = false;

		// container config - set once when the container is added
		this.config = containerConfig;

		// optional filter function to limit the spottable candidates for this container
		this.filter = navigableFilter;

		// private hash of spotlight DOM attributes
		this.attr = {
			'data-spotlight-container': true
		};

		// Used to indicate that we want to stop propagation on blur events that occur as a
		// result of this component imperatively blurring itself on focus when spotlightDisabled
		this.shouldPreventBlur = false;
	}

	get attributes () {
		return this.attr;
	}

	setProps (props: SpotlightContainerProps) {
		const {disabled, id, muted, restrict} = props;
		this.props = props;

		if (this.id == null || (id && this.id !== id)) {
			if (this.id) {
				this.releaseContainer();
			}

			this.id = Spotlight.add({
				...this.config,
				id,
				restrict,
				navigableFilter: this.navigableFilter
			});
			this.preserveId = !!(this.canPreserveId && this.id === id);
		} else {
			Spotlight.set(this.id, {restrict});
		}

		this.attr['data-spotlight-id'] = this.id;
		this.attr['data-spotlight-container-disabled'] = disabled;
		this.attr['data-spotlight-container-muted'] = muted;
	}

	unload () {
		this.releaseContainer();
	}

	releaseContainer () {
		if (this.preserveId) {
			Spotlight.unmount(this.id!);
		} else {
			Spotlight.remove(this.id!);
		}
	}

	navigableFilter = (elem: Element) => {
		// If the component to which this was applied specified a navigableFilter, run it
		if (typeof this.filter === 'function') {
			if (this.filter(elem) === false) {
				return false;
			}
		}

		return true;
	};

	silentBlur ({target}: {target: HTMLElement}) {
		this.shouldPreventBlur = true;
		target.blur();
		this.shouldPreventBlur = false;
	}

	onBlurCapture = (ev: any) => {
		if (this.shouldPreventBlur) {
			stop(ev);

			return false;
		}

		return true;
	};

	onFocusCapture = (ev: any) => {
		if (this.props.disabled === true) {
			stop(ev);
			this.silentBlur(ev);

			return false;
		}

		return true;
	};

	onPointerEnter = handle(
		isNewPointerPosition,
		() => Spotlight.setActiveContainer(this.id!)
	).bindAs(this, 'onPointerEnter');

	onPointerLeave = handle(
		not(forProp('restrict', 'self-only')),
		isNewPointerPosition,
		(ev: Event | null) => {
			const parentContainer = ((ev?.currentTarget as HTMLElement | null)?.parentNode as Element | null)?.closest('[data-spotlight-container]') as HTMLElement | null;
			let activeContainer = Spotlight.getActiveContainer();

			// if this container is wrapped by another and this is the currently active
			// container, move the active container to the parent
			if (parentContainer && activeContainer === this.id) {
				Spotlight.setActiveContainer(parentContainer.dataset.spotlightId as string);
			}
		}
	).bindAs(this, 'onPointerLeave');
}

export default SpotlightContainer;
export {
	SpotlightContainer
};
